# Generated by Django 6.0.5 on 2026-05-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('subject', models.CharField(choices=[('Математика', 'Математика'), ('Русский язык', 'Русский язык'), ('Обществознание', 'Обществознание'), ('Физика', 'Физика'), ('Информатика', 'Информатика'), ('Английский язык', 'Английский язык'), ('Химия', 'Химия'), ('Биология', 'Биология'), ('История', 'История'), ('Литература', 'Литература')], max_length=50, verbose_name='Предмет')),
                ('grade', models.CharField(choices=[('9', '9 класс (ОГЭ)'), ('10', '10 класс (ЕГЭ)'), ('11', '11 класс (ЕГЭ)')], max_length=2, verbose_name='Класс')),
                ('brief', models.TextField(blank=True, verbose_name='Пожелания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
